<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Language;

use Atlas\Table\Row;

/**
 * @property mixed $language_id int(10,0) unsigned NOT NULL
 * @property mixed $language_url char(255) NOT NULL
 * @property mixed $language_name char(255) NOT NULL
 * @property mixed $language_entity int(10,0) unsigned NOT NULL
 */
class LanguageRow extends Row
{
    protected $cols = [
        'language_id' => null,
        'language_url' => null,
        'language_name' => null,
        'language_entity' => null,
    ];
}
