<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Language;

/**
 * @property mixed $language_id int(10,0) unsigned NOT NULL
 * @property mixed $language_url char(255) NOT NULL
 * @property mixed $language_name char(255) NOT NULL
 * @property mixed $language_entity int(10,0) unsigned NOT NULL
 */
trait LanguageFields
{
}
