<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Language;

use Atlas\Table\Table;

/**
 * @method LanguageRow|null fetchRow($primaryVal)
 * @method LanguageRow[] fetchRows(array $primaryVals)
 * @method LanguageTableSelect select(array $whereEquals = [])
 * @method LanguageRow newRow(array $cols = [])
 * @method LanguageRow newSelectedRow(array $cols)
 */
class LanguageTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'languages';

    const COLUMNS = [
        'language_id' => array (
  'name' => 'language_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'language_url' => array (
  'name' => 'language_url',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'language_name' => array (
  'name' => 'language_name',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'language_entity' => array (
  'name' => 'language_entity',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'language_id',
        'language_url',
        'language_name',
        'language_entity',
    ];

    const COLUMN_DEFAULTS = [
        'language_id' => null,
        'language_url' => null,
        'language_name' => null,
        'language_entity' => null,
    ];

    const PRIMARY_KEY = [
        'language_id',
    ];

    const AUTOINC_COLUMN = 'language_id';

    const AUTOINC_SEQUENCE = null;
}
