<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\User;

/**
 * @property mixed $user_id bigint(20,0) unsigned NOT NULL
 * @property mixed $role_id bigint(20,0) unsigned
 * @property mixed $avatar varchar(255)
 * @property mixed $name varchar(255) NOT NULL
 * @property mixed $last_name varchar(255)
 * @property mixed $phone varchar(255)
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $email_verified_at timestamp
 * @property mixed $password varchar(255)
 * @property mixed $two_factor_secret text(65535)
 * @property mixed $two_factor_recovery_codes text(65535)
 * @property mixed $two_factor_confirmed_at timestamp
 * @property mixed $user_last_seen datetime
 * @property mixed $notification_last_seen datetime
 * @property mixed $messages_last_seen datetime
 * @property mixed $user_ip varchar(255)
 * @property mixed $user_profile_entity int(10,0) unsigned
 * @property mixed $user_type enum(8)
 * @property mixed $active tinyint(3,0) NOT NULL
 * @property mixed $remember_token varchar(100)
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
trait UserFields
{
}
