<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\User;

use Atlas\Table\Row;

/**
 * @property mixed $user_id bigint(20,0) unsigned NOT NULL
 * @property mixed $role_id bigint(20,0) unsigned
 * @property mixed $avatar varchar(255)
 * @property mixed $name varchar(255) NOT NULL
 * @property mixed $last_name varchar(255)
 * @property mixed $phone varchar(255)
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $email_verified_at timestamp
 * @property mixed $password varchar(255)
 * @property mixed $two_factor_secret text(65535)
 * @property mixed $two_factor_recovery_codes text(65535)
 * @property mixed $two_factor_confirmed_at timestamp
 * @property mixed $user_last_seen datetime
 * @property mixed $notification_last_seen datetime
 * @property mixed $messages_last_seen datetime
 * @property mixed $user_ip varchar(255)
 * @property mixed $user_profile_entity int(10,0) unsigned
 * @property mixed $user_type enum(8)
 * @property mixed $active tinyint(3,0) NOT NULL
 * @property mixed $remember_token varchar(100)
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
class UserRow extends Row
{
    protected $cols = [
        'user_id' => null,
        'role_id' => null,
        'avatar' => null,
        'name' => null,
        'last_name' => null,
        'phone' => null,
        'email' => null,
        'email_verified_at' => null,
        'password' => null,
        'two_factor_secret' => null,
        'two_factor_recovery_codes' => null,
        'two_factor_confirmed_at' => null,
        'user_last_seen' => null,
        'notification_last_seen' => null,
        'messages_last_seen' => null,
        'user_ip' => null,
        'user_profile_entity' => null,
        'user_type' => null,
        'active' => 1,
        'remember_token' => null,
        'created_at' => null,
        'updated_at' => null,
    ];
}
