<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Entity;

/**
 * @property mixed $entity_id int(10,0) unsigned NOT NULL
 * @property mixed $entity_creation_date datetime NOT NULL
 * @property mixed $entity_creator int(10,0) unsigned NOT NULL
 * @property mixed $entity_update_date datetime
 * @property mixed $entity_updater int(10,0) unsigned
 * @property mixed $entity_order int(10,0) unsigned NOT NULL
 * @property mixed $entity_parent int(10,0) unsigned NOT NULL
 * @property mixed $entity_visible tinyint(3,0) unsigned NOT NULL
 * @property mixed $entity_type char(50)
 * @property mixed $entity_sub_type char(50)
 * @property mixed $entity_role tinyint(3,0) unsigned
 * @property mixed $entity_removable tinyint(3,0) unsigned NOT NULL
 * @property mixed $entity_is_widget tinyint(3,0) unsigned NOT NULL
 */
trait EntityFields
{
}
