<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Entity;

use Atlas\Table\Table;

/**
 * @method EntityRow|null fetchRow($primaryVal)
 * @method EntityRow[] fetchRows(array $primaryVals)
 * @method EntityTableSelect select(array $whereEquals = [])
 * @method EntityRow newRow(array $cols = [])
 * @method EntityRow newSelectedRow(array $cols)
 */
class EntityTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'entities';

    const COLUMNS = [
        'entity_id' => array (
  'name' => 'entity_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'entity_creation_date' => array (
  'name' => 'entity_creation_date',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_creator' => array (
  'name' => 'entity_creator',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_update_date' => array (
  'name' => 'entity_update_date',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_updater' => array (
  'name' => 'entity_updater',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_order' => array (
  'name' => 'entity_order',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_parent' => array (
  'name' => 'entity_parent',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_visible' => array (
  'name' => 'entity_visible',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_type' => array (
  'name' => 'entity_type',
  'type' => 'char',
  'size' => 50,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_sub_type' => array (
  'name' => 'entity_sub_type',
  'type' => 'char',
  'size' => 50,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_role' => array (
  'name' => 'entity_role',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_removable' => array (
  'name' => 'entity_removable',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'entity_is_widget' => array (
  'name' => 'entity_is_widget',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'entity_id',
        'entity_creation_date',
        'entity_creator',
        'entity_update_date',
        'entity_updater',
        'entity_order',
        'entity_parent',
        'entity_visible',
        'entity_type',
        'entity_sub_type',
        'entity_role',
        'entity_removable',
        'entity_is_widget',
    ];

    const COLUMN_DEFAULTS = [
        'entity_id' => null,
        'entity_creation_date' => null,
        'entity_creator' => null,
        'entity_update_date' => null,
        'entity_updater' => null,
        'entity_order' => null,
        'entity_parent' => null,
        'entity_visible' => null,
        'entity_type' => null,
        'entity_sub_type' => null,
        'entity_role' => null,
        'entity_removable' => null,
        'entity_is_widget' => null,
    ];

    const PRIMARY_KEY = [
        'entity_id',
    ];

    const AUTOINC_COLUMN = 'entity_id';

    const AUTOINC_SEQUENCE = null;
}
