<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Mediable;

use Atlas\Table\Row;

/**
 * @property mixed $media_id int(10,0) unsigned NOT NULL
 * @property mixed $mediable_type varchar(255) NOT NULL
 * @property mixed $mediable_id int(10,0) unsigned NOT NULL
 * @property mixed $tag varchar(255) NOT NULL
 * @property mixed $order int(10,0) unsigned NOT NULL
 */
class MediableRow extends Row
{
    protected $cols = [
        'media_id' => null,
        'mediable_type' => null,
        'mediable_id' => null,
        'tag' => null,
        'order' => null,
    ];
}
