<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Mediable;

use Atlas\Table\Table;

/**
 * @method MediableRow|null fetchRow($primaryVal)
 * @method MediableRow[] fetchRows(array $primaryVals)
 * @method MediableTableSelect select(array $whereEquals = [])
 * @method MediableRow newRow(array $cols = [])
 * @method MediableRow newSelectedRow(array $cols)
 */
class MediableTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'mediables';

    const COLUMNS = [
        'media_id' => array (
  'name' => 'media_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'mediable_type' => array (
  'name' => 'mediable_type',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'mediable_id' => array (
  'name' => 'mediable_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'tag' => array (
  'name' => 'tag',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'order' => array (
  'name' => 'order',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'media_id',
        'mediable_type',
        'mediable_id',
        'tag',
        'order',
    ];

    const COLUMN_DEFAULTS = [
        'media_id' => null,
        'mediable_type' => null,
        'mediable_id' => null,
        'tag' => null,
        'order' => null,
    ];

    const PRIMARY_KEY = [
        'media_id',
        'mediable_type',
        'mediable_id',
        'tag',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
