<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Migration;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $migration varchar(255) NOT NULL
 * @property mixed $batch int(10,0) NOT NULL
 */
trait MigrationFields
{
}
