<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Migration;

use Atlas\Table\Table;

/**
 * @method MigrationRow|null fetchRow($primaryVal)
 * @method MigrationRow[] fetchRows(array $primaryVals)
 * @method MigrationTableSelect select(array $whereEquals = [])
 * @method MigrationRow newRow(array $cols = [])
 * @method MigrationRow newSelectedRow(array $cols)
 */
class MigrationTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'migrations';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'migration' => array (
  'name' => 'migration',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'batch' => array (
  'name' => 'batch',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'migration',
        'batch',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'migration' => null,
        'batch' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
