<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Migration;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $migration varchar(255) NOT NULL
 * @property mixed $batch int(10,0) NOT NULL
 */
class MigrationRow extends Row
{
    protected $cols = [
        'id' => null,
        'migration' => null,
        'batch' => null,
    ];
}
