<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\PasswordResetToken;

use Atlas\Table\Row;

/**
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $token varchar(255) NOT NULL
 * @property mixed $created_at timestamp
 */
class PasswordResetTokenRow extends Row
{
    protected $cols = [
        'email' => null,
        'token' => null,
        'created_at' => null,
    ];
}
