<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\PasswordResetToken;

use Atlas\Table\Table;

/**
 * @method PasswordResetTokenRow|null fetchRow($primaryVal)
 * @method PasswordResetTokenRow[] fetchRows(array $primaryVals)
 * @method PasswordResetTokenTableSelect select(array $whereEquals = [])
 * @method PasswordResetTokenRow newRow(array $cols = [])
 * @method PasswordResetTokenRow newSelectedRow(array $cols)
 */
class PasswordResetTokenTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'password_reset_tokens';

    const COLUMNS = [
        'email' => array (
  'name' => 'email',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'token' => array (
  'name' => 'token',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'created_at' => array (
  'name' => 'created_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'email',
        'token',
        'created_at',
    ];

    const COLUMN_DEFAULTS = [
        'email' => null,
        'token' => null,
        'created_at' => null,
    ];

    const PRIMARY_KEY = [
        'email',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
