<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Role;

use Atlas\Table\Row;

/**
 * @property mixed $role_id bigint(20,0) unsigned NOT NULL
 * @property mixed $role_name varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
class RoleRow extends Row
{
    protected $cols = [
        'role_id' => null,
        'role_name' => null,
        'slug' => null,
        'created_at' => null,
        'updated_at' => null,
    ];
}
