<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Role;

/**
 * @property mixed $role_id bigint(20,0) unsigned NOT NULL
 * @property mixed $role_name varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
trait RoleFields
{
}
