<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\UserRole;

use Atlas\Table\Table;

/**
 * @method UserRoleRow|null fetchRow($primaryVal)
 * @method UserRoleRow[] fetchRows(array $primaryVals)
 * @method UserRoleTableSelect select(array $whereEquals = [])
 * @method UserRoleRow newRow(array $cols = [])
 * @method UserRoleRow newSelectedRow(array $cols)
 */
class UserRoleTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'user_roles';

    const COLUMNS = [
        'ur_user' => array (
  'name' => 'ur_user',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'ur_role' => array (
  'name' => 'ur_role',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'ur_user',
        'ur_role',
    ];

    const COLUMN_DEFAULTS = [
        'ur_user' => null,
        'ur_role' => null,
    ];

    const PRIMARY_KEY = [
        'ur_user',
        'ur_role',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
