<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\UserRole;

/**
 * @property mixed $ur_user int(10,0) unsigned NOT NULL
 * @property mixed $ur_role tinyint(3,0) unsigned NOT NULL
 */
trait UserRoleFields
{
}
