<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityDataLang;

use Atlas\Table\Table;

/**
 * @method EntityDataLangRow|null fetchRow($primaryVal)
 * @method EntityDataLangRow[] fetchRows(array $primaryVals)
 * @method EntityDataLangTableSelect select(array $whereEquals = [])
 * @method EntityDataLangRow newRow(array $cols = [])
 * @method EntityDataLangRow newSelectedRow(array $cols)
 */
class EntityDataLangTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'entity_data_lang';

    const COLUMNS = [
        'edl_entity' => array (
  'name' => 'edl_entity',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'edl_lang' => array (
  'name' => 'edl_lang',
  'type' => 'tinyint unsigned',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'edl_title' => array (
  'name' => 'edl_title',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_file' => array (
  'name' => 'edl_file',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_char_1' => array (
  'name' => 'edl_char_1',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_char_2' => array (
  'name' => 'edl_char_2',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_char_3' => array (
  'name' => 'edl_char_3',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_text_1' => array (
  'name' => 'edl_text_1',
  'type' => 'longtext',
  'size' => 4294967295,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_text_2' => array (
  'name' => 'edl_text_2',
  'type' => 'longtext',
  'size' => 4294967295,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_text_3' => array (
  'name' => 'edl_text_3',
  'type' => 'longtext',
  'size' => 4294967295,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_text_4' => array (
  'name' => 'edl_text_4',
  'type' => 'longtext',
  'size' => 4294967295,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'edl_text_5' => array (
  'name' => 'edl_text_5',
  'type' => 'longtext',
  'size' => 4294967295,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'edl_entity',
        'edl_lang',
        'edl_title',
        'edl_file',
        'edl_char_1',
        'edl_char_2',
        'edl_char_3',
        'edl_text_1',
        'edl_text_2',
        'edl_text_3',
        'edl_text_4',
        'edl_text_5',
    ];

    const COLUMN_DEFAULTS = [
        'edl_entity' => null,
        'edl_lang' => null,
        'edl_title' => null,
        'edl_file' => null,
        'edl_char_1' => null,
        'edl_char_2' => null,
        'edl_char_3' => null,
        'edl_text_1' => null,
        'edl_text_2' => null,
        'edl_text_3' => null,
        'edl_text_4' => null,
        'edl_text_5' => null,
    ];

    const PRIMARY_KEY = [
        'edl_entity',
        'edl_lang',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
