<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityDataLang;

use Atlas\Table\Row;

/**
 * @property mixed $edl_entity int(10,0) unsigned NOT NULL
 * @property mixed $edl_lang tinyint(3,0) unsigned NOT NULL
 * @property mixed $edl_title char(255)
 * @property mixed $edl_file char(255)
 * @property mixed $edl_char_1 char(255)
 * @property mixed $edl_char_2 char(255)
 * @property mixed $edl_char_3 char(255)
 * @property mixed $edl_text_1 longtext(4294967295)
 * @property mixed $edl_text_2 longtext(4294967295)
 * @property mixed $edl_text_3 longtext(4294967295)
 * @property mixed $edl_text_4 longtext(4294967295)
 * @property mixed $edl_text_5 longtext(4294967295)
 */
class EntityDataLangRow extends Row
{
    protected $cols = [
        'edl_entity' => null,
        'edl_lang' => null,
        'edl_title' => null,
        'edl_file' => null,
        'edl_char_1' => null,
        'edl_char_2' => null,
        'edl_char_3' => null,
        'edl_text_1' => null,
        'edl_text_2' => null,
        'edl_text_3' => null,
        'edl_text_4' => null,
        'edl_text_5' => null,
    ];
}
