<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\PasswordReset;

/**
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $token varchar(255) NOT NULL
 * @property mixed $created_at timestamp
 */
trait PasswordResetFields
{
}
