<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Favorite;

use Atlas\Table\Table;

/**
 * @method FavoriteRow|null fetchRow($primaryVal)
 * @method FavoriteRow[] fetchRows(array $primaryVals)
 * @method FavoriteTableSelect select(array $whereEquals = [])
 * @method FavoriteRow newRow(array $cols = [])
 * @method FavoriteRow newSelectedRow(array $cols)
 */
class FavoriteTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'favorites';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'bigint unsigned',
  'size' => 20,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'type' => array (
  'name' => 'type',
  'type' => 'enum',
  'size' => 6,
  'scale' => NULL,
  'notnull' => false,
  'default' => 'Game',
  'autoinc' => false,
  'primary' => false,
  'options' => 
  array (
    0 => '\'File\'',
    1 => '\'Game\'',
    2 => '\'Folder\'',
  ),
),
        'client_id' => array (
  'name' => 'client_id',
  'type' => 'bigint unsigned',
  'size' => 20,
  'scale' => 0,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'ed_entity' => array (
  'name' => 'ed_entity',
  'type' => 'bigint unsigned',
  'size' => 20,
  'scale' => 0,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'path' => array (
  'name' => 'path',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'created_at' => array (
  'name' => 'created_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'updated_at' => array (
  'name' => 'updated_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'type',
        'client_id',
        'ed_entity',
        'path',
        'created_at',
        'updated_at',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'type' => 'Game',
        'client_id' => null,
        'ed_entity' => null,
        'path' => null,
        'created_at' => null,
        'updated_at' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
