<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Favorite;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $type enum(6)
 * @property mixed $client_id bigint(20,0) unsigned
 * @property mixed $ed_entity bigint(20,0) unsigned
 * @property mixed $path varchar(255)
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
trait FavoriteFields
{
}
