<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Medium;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $disk varchar(32) NOT NULL
 * @property mixed $directory varchar(255) NOT NULL
 * @property mixed $filename varchar(255) NOT NULL
 * @property mixed $extension varchar(32) NOT NULL
 * @property mixed $mime_type varchar(128) NOT NULL
 * @property mixed $aggregate_type varchar(32) NOT NULL
 * @property mixed $size int(10,0) unsigned NOT NULL
 * @property mixed $variant_name varchar(255)
 * @property mixed $original_media_id int(10,0) unsigned
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
trait MediumFields
{
}
