<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Medium;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $disk varchar(32) NOT NULL
 * @property mixed $directory varchar(255) NOT NULL
 * @property mixed $filename varchar(255) NOT NULL
 * @property mixed $extension varchar(32) NOT NULL
 * @property mixed $mime_type varchar(128) NOT NULL
 * @property mixed $aggregate_type varchar(32) NOT NULL
 * @property mixed $size int(10,0) unsigned NOT NULL
 * @property mixed $variant_name varchar(255)
 * @property mixed $original_media_id int(10,0) unsigned
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
class MediumRow extends Row
{
    protected $cols = [
        'id' => null,
        'disk' => null,
        'directory' => null,
        'filename' => null,
        'extension' => null,
        'mime_type' => null,
        'aggregate_type' => null,
        'size' => null,
        'variant_name' => null,
        'original_media_id' => null,
        'created_at' => null,
        'updated_at' => null,
    ];
}
