<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityGalleryLang;

use Atlas\Table\Table;

/**
 * @method EntityGalleryLangRow|null fetchRow($primaryVal)
 * @method EntityGalleryLangRow[] fetchRows(array $primaryVals)
 * @method EntityGalleryLangTableSelect select(array $whereEquals = [])
 * @method EntityGalleryLangRow newRow(array $cols = [])
 * @method EntityGalleryLangRow newSelectedRow(array $cols)
 */
class EntityGalleryLangTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'entity_gallery_lang';

    const COLUMNS = [
        'egl_gallery' => array (
  'name' => 'egl_gallery',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'egl_language' => array (
  'name' => 'egl_language',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'egl_title' => array (
  'name' => 'egl_title',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'egl_gallery',
        'egl_language',
        'egl_title',
    ];

    const COLUMN_DEFAULTS = [
        'egl_gallery' => null,
        'egl_language' => null,
        'egl_title' => null,
    ];

    const PRIMARY_KEY = [
        'egl_gallery',
        'egl_language',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
