<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\FailedJob;

use Atlas\Table\Table;

/**
 * @method FailedJobRow|null fetchRow($primaryVal)
 * @method FailedJobRow[] fetchRows(array $primaryVals)
 * @method FailedJobTableSelect select(array $whereEquals = [])
 * @method FailedJobRow newRow(array $cols = [])
 * @method FailedJobRow newSelectedRow(array $cols)
 */
class FailedJobTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'failed_jobs';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'bigint unsigned',
  'size' => 20,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'uuid' => array (
  'name' => 'uuid',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'connection' => array (
  'name' => 'connection',
  'type' => 'text',
  'size' => 65535,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'queue' => array (
  'name' => 'queue',
  'type' => 'text',
  'size' => 65535,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'payload' => array (
  'name' => 'payload',
  'type' => 'longtext',
  'size' => 4294967295,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'exception' => array (
  'name' => 'exception',
  'type' => 'longtext',
  'size' => 4294967295,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'failed_at' => array (
  'name' => 'failed_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'uuid',
        'connection',
        'queue',
        'payload',
        'exception',
        'failed_at',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'uuid' => null,
        'connection' => null,
        'queue' => null,
        'payload' => null,
        'exception' => null,
        'failed_at' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
