<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\FailedJob;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $uuid varchar(255) NOT NULL
 * @property mixed $connection text(65535) NOT NULL
 * @property mixed $queue text(65535) NOT NULL
 * @property mixed $payload longtext(4294967295) NOT NULL
 * @property mixed $exception longtext(4294967295) NOT NULL
 * @property mixed $failed_at timestamp NOT NULL
 */
trait FailedJobFields
{
}
