<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntitySeo;

/**
 * @property mixed $es_entity int(10,0) unsigned NOT NULL
 * @property mixed $es_lang int(10,0) unsigned NOT NULL
 * @property mixed $es_url char(255)
 * @property mixed $es_title char(255)
 * @property mixed $es_keywords mediumtext(16777215)
 * @property mixed $es_description mediumtext(16777215)
 */
trait EntitySeoFields
{
}
