<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntitySeo;

use Atlas\Table\Table;

/**
 * @method EntitySeoRow|null fetchRow($primaryVal)
 * @method EntitySeoRow[] fetchRows(array $primaryVals)
 * @method EntitySeoTableSelect select(array $whereEquals = [])
 * @method EntitySeoRow newRow(array $cols = [])
 * @method EntitySeoRow newSelectedRow(array $cols)
 */
class EntitySeoTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'entity_seo';

    const COLUMNS = [
        'es_entity' => array (
  'name' => 'es_entity',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'es_lang' => array (
  'name' => 'es_lang',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'es_url' => array (
  'name' => 'es_url',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'es_title' => array (
  'name' => 'es_title',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'es_keywords' => array (
  'name' => 'es_keywords',
  'type' => 'mediumtext',
  'size' => 16777215,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'es_description' => array (
  'name' => 'es_description',
  'type' => 'mediumtext',
  'size' => 16777215,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'es_entity',
        'es_lang',
        'es_url',
        'es_title',
        'es_keywords',
        'es_description',
    ];

    const COLUMN_DEFAULTS = [
        'es_entity' => null,
        'es_lang' => null,
        'es_url' => null,
        'es_title' => null,
        'es_keywords' => null,
        'es_description' => null,
    ];

    const PRIMARY_KEY = [
        'es_entity',
        'es_lang',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
