<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\PersonalAccessToken;

use Atlas\Table\Table;

/**
 * @method PersonalAccessTokenRow|null fetchRow($primaryVal)
 * @method PersonalAccessTokenRow[] fetchRows(array $primaryVals)
 * @method PersonalAccessTokenTableSelect select(array $whereEquals = [])
 * @method PersonalAccessTokenRow newRow(array $cols = [])
 * @method PersonalAccessTokenRow newSelectedRow(array $cols)
 */
class PersonalAccessTokenTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'personal_access_tokens';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'bigint unsigned',
  'size' => 20,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'tokenable_type' => array (
  'name' => 'tokenable_type',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'tokenable_id' => array (
  'name' => 'tokenable_id',
  'type' => 'bigint unsigned',
  'size' => 20,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'name' => array (
  'name' => 'name',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'token' => array (
  'name' => 'token',
  'type' => 'varchar',
  'size' => 64,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'abilities' => array (
  'name' => 'abilities',
  'type' => 'text',
  'size' => 65535,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'last_used_at' => array (
  'name' => 'last_used_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'expires_at' => array (
  'name' => 'expires_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'created_at' => array (
  'name' => 'created_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'updated_at' => array (
  'name' => 'updated_at',
  'type' => 'timestamp',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'tokenable_type',
        'tokenable_id',
        'name',
        'token',
        'abilities',
        'last_used_at',
        'expires_at',
        'created_at',
        'updated_at',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'tokenable_type' => null,
        'tokenable_id' => null,
        'name' => null,
        'token' => null,
        'abilities' => null,
        'last_used_at' => null,
        'expires_at' => null,
        'created_at' => null,
        'updated_at' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
