<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\PersonalAccessToken;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $tokenable_type varchar(255) NOT NULL
 * @property mixed $tokenable_id bigint(20,0) unsigned NOT NULL
 * @property mixed $name varchar(255) NOT NULL
 * @property mixed $token varchar(64) NOT NULL
 * @property mixed $abilities text(65535)
 * @property mixed $last_used_at timestamp
 * @property mixed $expires_at timestamp
 * @property mixed $created_at timestamp
 * @property mixed $updated_at timestamp
 */
trait PersonalAccessTokenFields
{
}
