<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityGallery;

use Atlas\Table\Table;

/**
 * @method EntityGalleryRow|null fetchRow($primaryVal)
 * @method EntityGalleryRow[] fetchRows(array $primaryVals)
 * @method EntityGalleryTableSelect select(array $whereEquals = [])
 * @method EntityGalleryRow newRow(array $cols = [])
 * @method EntityGalleryRow newSelectedRow(array $cols)
 */
class EntityGalleryTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'entity_gallery';

    const COLUMNS = [
        'eg_id' => array (
  'name' => 'eg_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'eg_entity' => array (
  'name' => 'eg_entity',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'eg_path' => array (
  'name' => 'eg_path',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'eg_order' => array (
  'name' => 'eg_order',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'eg_id',
        'eg_entity',
        'eg_path',
        'eg_order',
    ];

    const COLUMN_DEFAULTS = [
        'eg_id' => null,
        'eg_entity' => null,
        'eg_path' => null,
        'eg_order' => null,
    ];

    const PRIMARY_KEY = [
        'eg_id',
    ];

    const AUTOINC_COLUMN = 'eg_id';

    const AUTOINC_SEQUENCE = null;
}
