<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityDatum;

use Atlas\Table\Row;

/**
 * @property mixed $ed_entity int(10,0) unsigned NOT NULL
 * @property mixed $ed_title char(255)
 * @property mixed $ed_image char(255)
 * @property mixed $ed_char_1 char(255)
 * @property mixed $ed_char_2 char(255)
 * @property mixed $ed_char_3 char(255)
 * @property mixed $ed_char_4 char(255)
 * @property mixed $ed_char_5 char(255)
 * @property mixed $ed_text_1 longtext(4294967295)
 * @property mixed $ed_text_2 longtext(4294967295)
 * @property mixed $ed_text_3 longtext(4294967295)
 * @property mixed $ed_text_4 longtext(4294967295)
 * @property mixed $ed_text_5 longtext(4294967295)
 * @property mixed $ed_number_1 int(10,0) unsigned
 * @property mixed $ed_number_2 int(10,0) unsigned
 * @property mixed $ed_number_3 int(10,0) unsigned
 * @property mixed $ed_number_4 int(10,0) unsigned
 * @property mixed $ed_number_5 int(10,0) unsigned
 * @property mixed $ed_datetime_1 datetime
 * @property mixed $ed_datetime_2 date
 * @property mixed $ed_datetime_3 date
 * @property mixed $ed_datetime_4 time
 * @property mixed $ed_datetime_5 time
 */
class EntityDatumRow extends Row
{
    protected $cols = [
        'ed_entity' => null,
        'ed_title' => null,
        'ed_image' => null,
        'ed_char_1' => null,
        'ed_char_2' => null,
        'ed_char_3' => null,
        'ed_char_4' => null,
        'ed_char_5' => null,
        'ed_text_1' => null,
        'ed_text_2' => null,
        'ed_text_3' => null,
        'ed_text_4' => null,
        'ed_text_5' => null,
        'ed_number_1' => null,
        'ed_number_2' => null,
        'ed_number_3' => null,
        'ed_number_4' => null,
        'ed_number_5' => null,
        'ed_datetime_1' => null,
        'ed_datetime_2' => null,
        'ed_datetime_3' => null,
        'ed_datetime_4' => null,
        'ed_datetime_5' => null,
    ];
}
