<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityWord;

/**
 * @property mixed $ew_entity int(10,0) unsigned NOT NULL
 * @property mixed $ew_index int(10,0) unsigned NOT NULL
 * @property mixed $ew_lang int(10,0) unsigned NOT NULL
 * @property mixed $ew_value char(255)
 */
trait EntityWordFields
{
}
