<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityWord;

use Atlas\Table\Table;

/**
 * @method EntityWordRow|null fetchRow($primaryVal)
 * @method EntityWordRow[] fetchRows(array $primaryVals)
 * @method EntityWordTableSelect select(array $whereEquals = [])
 * @method EntityWordRow newRow(array $cols = [])
 * @method EntityWordRow newSelectedRow(array $cols)
 */
class EntityWordTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'entity_words';

    const COLUMNS = [
        'ew_entity' => array (
  'name' => 'ew_entity',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'ew_index' => array (
  'name' => 'ew_index',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'ew_lang' => array (
  'name' => 'ew_lang',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'ew_value' => array (
  'name' => 'ew_value',
  'type' => 'char',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'ew_entity',
        'ew_index',
        'ew_lang',
        'ew_value',
    ];

    const COLUMN_DEFAULTS = [
        'ew_entity' => null,
        'ew_index' => null,
        'ew_lang' => null,
        'ew_value' => null,
    ];

    const PRIMARY_KEY = [
        'ew_entity',
        'ew_index',
        'ew_lang',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
