<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityOption;

use Atlas\Table\Row;

/**
 * @property mixed $eo_id int(10,0) unsigned NOT NULL
 * @property mixed $eo_entity int(10,0) unsigned NOT NULL
 * @property mixed $eo_key char(50) NOT NULL
 * @property mixed $eo_value int(10,0) unsigned NOT NULL
 * @property mixed $eo_order int(10,0) unsigned NOT NULL
 */
class EntityOptionRow extends Row
{
    protected $cols = [
        'eo_id' => null,
        'eo_entity' => null,
        'eo_key' => null,
        'eo_value' => null,
        'eo_order' => null,
    ];
}
