<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityOption;

use Atlas\Table\Table;

/**
 * @method EntityOptionRow|null fetchRow($primaryVal)
 * @method EntityOptionRow[] fetchRows(array $primaryVals)
 * @method EntityOptionTableSelect select(array $whereEquals = [])
 * @method EntityOptionRow newRow(array $cols = [])
 * @method EntityOptionRow newSelectedRow(array $cols)
 */
class EntityOptionTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'entity_options';

    const COLUMNS = [
        'eo_id' => array (
  'name' => 'eo_id',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'eo_entity' => array (
  'name' => 'eo_entity',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'eo_key' => array (
  'name' => 'eo_key',
  'type' => 'char',
  'size' => 50,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'eo_value' => array (
  'name' => 'eo_value',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'eo_order' => array (
  'name' => 'eo_order',
  'type' => 'int unsigned',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'eo_id',
        'eo_entity',
        'eo_key',
        'eo_value',
        'eo_order',
    ];

    const COLUMN_DEFAULTS = [
        'eo_id' => null,
        'eo_entity' => null,
        'eo_key' => null,
        'eo_value' => null,
        'eo_order' => null,
    ];

    const PRIMARY_KEY = [
        'eo_id',
    ];

    const AUTOINC_COLUMN = 'eo_id';

    const AUTOINC_SEQUENCE = null;
}
