<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\EntityOption;

/**
 * @property mixed $eo_id int(10,0) unsigned NOT NULL
 * @property mixed $eo_entity int(10,0) unsigned NOT NULL
 * @property mixed $eo_key char(50) NOT NULL
 * @property mixed $eo_value int(10,0) unsigned NOT NULL
 * @property mixed $eo_order int(10,0) unsigned NOT NULL
 */
trait EntityOptionFields
{
}
